---
development:
  adapter: mysql2
  encoding: utf8
  database: fat_free_crm_development
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
test:
  adapter: mysql2
  encoding: utf8
  database: fat_free_crm_test
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
production:
  adapter: mysql2
  encoding: utf8
  database: fat_free_crm_production
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
staging:
  adapter: mysql2
  encoding: utf8
  database: fat_free_crm_staging
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
