---
development:
  adapter: postgresql
  database: fat_free_crm_development
  username: 
  password: 
  host: localhost
  port: 5432
  schema_search_path: public
  min_messages: warning
test:
  adapter: postgresql
  database: fat_free_crm_test
  username: 
  password: 
  host: localhost
  port: 5432
  schema_search_path: public
  min_messages: warning
production:
  adapter: postgresql
  database: fat_free_crm_production
  username: 
  password: 
  host: localhost
  port: 5432
  schema_search_path: public
  min_messages: warning
staging:
  adapter: postgresql
  database: fat_free_crm_staging
  username: 
  password: 
  host: localhost
  port: 5432
  schema_search_path: public
  min_messages: warning
