---
development:
  adapter: sqlite3
  database: db/fat_free_crm_development.sqlite3
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: db/fat_free_crm_test.sqlite3
  pool: 5
  timeout: 5000
production:
  adapter: sqlite3
  database: db/fat_free_crm_production.sqlite3
  pool: 5
  timeout: 5000
staging:
  adapter: sqlite3
  database: db/fat_free_crm_staging.sqlite3
  pool: 5
  timeout: 5000
