---
:host: ''
:base_url: ''
:locale: en-US
:smtp:
  :address: ''
  :from: ''
  :enable_starttls_auto: true
  :port: ''
  :authentication: :plain
  :user_name: ''
  :password: ''
:email_dropbox:
  :server: ''
  :port: ''
  :ssl: ''
  :address: ''
  :user: ''
  :password: ''
  :scan_folder: ''
  :attach_to_account: ''
:email_comment_replies:
  :server: ''
  :port: ''
  :ssl: ''
  :address: ''
  :user: ''
  :password: ''
  :scan_folder: ''
:per_user_locale: false
:default_access: Public
:user_signup: :not_allowed
:compound_address: true
:task_calendar_with_time: true
:require_first_names: true
:require_last_names: true
:require_unique_account_names: true
:comments_visible_on_dashboard: false
:background_info: []
:tabs:
- :active: true
  :text: :tab_dashboard
  :icon: :fa-dashboard
  :url:
    :controller: home
- :active: false
  :text: :tab_tasks
  :icon: :fa-check-square-o
  :url:
    :controller: tasks
- :active: false
  :text: :tab_campaigns
  :icon: :fa-bar-chart-o
  :url:
    :controller: campaigns
- :active: false
  :text: :tab_leads
  :icon: :fa-tasks
  :url:
    :controller: leads
- :active: false
  :text: :tab_accounts
  :icon: :fa-users
  :url:
    :controller: accounts
- :active: false
  :text: :tab_contacts
  :icon: :fa-user
  :url:
    :controller: contacts
- :active: false
  :text: :tab_opportunities
  :icon: :fa-money
  :url:
    :controller: opportunities
- :active: false
  :text: :tab_team
  :icon: :fa-globe
  :url:
    :controller: users
    :action: opportunities_overview
:admin_tabs:
- :active: true
  :text: :admin_tab_users
  :icon: :fa-user
  :url:
    :controller: admin/users
- :active: true
  :text: :admin_tab_groups
  :icon: :fa-users
  :url:
    :controller: admin/groups
- :active: false
  :text: :admin_tab_fields
  :icon: :fa-list-alt
  :url:
    :controller: admin/fields
- :active: false
  :text: :admin_tab_tags
  :icon: :fa-tags
  :url:
    :controller: admin/tags
account_category:
- :affiliate
- :competitor
- :customer
- :partner
- :reseller
- :vendor
account_category_color:
  :affiliate: lavender
  :competitor: paleturquoise
  :customer: pink
  :partner: bisque
  :reseller: thistle
  :vendor: skyblue
campaign_status:
- :planned
- :started
- :completed
- :on_hold
- :called_off
campaign_status_color:
  :planned: Gold
  :started: Turquoise
  :completed: Lime
  :on_hold: Orchid
  :called_off: OrangeRed
lead_status:
- :new
- :contacted
- :converted
- :rejected
lead_status_color:
  :new: Silver
  :contacted: Turquoise
  :converted: Lime
  :rejected: OrangeRed
lead_source:
- :campaign
- :cold_call
- :conference
- :online
- :referral
- :self
- :web
- :word_of_mouth
- :other
opportunity_default_stage: :prospecting
opportunity_stage:
- :prospecting
- :analysis
- :presentation
- :proposal
- :negotiation
- :final_review
- :won
- :lost
opportunity_stage_color:
  :prospecting: Silver
  :analysis: PaleGoldenRod
  :presentation: Salmon
  :proposal: Gold
  :negotiation: Orchid
  :final_review: Turquoise
  :won: Lime
  :lost: OrangeRed
task_category:
- :call
- :email
- :follow_up
- :lunch
- :meeting
- :money
- :presentation
- :trip
task_category_color:
  :call: Silver
  :email: Turquoise
  :follow_up: Gold
  :lunch: Tomato
  :meeting: Orchid
  :money: Lime
  :presentation: Salmon
  :trip: Turquoise
task_bucket:
- :overdue
- :due_asap
- :due_today
- :due_tomorrow
- :due_this_week
- :due_next_week
- :due_later
task_completed:
- :completed_today
- :completed_yesterday
- :completed_last_week
- :completed_this_month
- :completed_last_month
